name: $(Date:yyyyMMdd)$(Rev:.r)_$(UBUNTU_SKU)_$(HYPERV_GENERATION)_$(FEATURE_FLAGS)_$(Build.SourceBranchName)
trigger: none


phases:
  - phase: build_vhd
    queue:
      name: ace-test
      timeoutInMinutes: 120
    steps:
      - task: UniversalPackages@0
        displayName: Download Asc Baseline
        inputs:
          command: download
          vstsFeed: ASMPackages
          vstsFeedPackage: asc-baseline
          vstsPackageVersion: '1.2.0'
          downloadDirectory: vhdbuilder/packer
      - bash: |
          ASC_BASELINE_TMP=vhdbuilder/packer/asc-baseline-1.0.0-master.354.amd64.deb
          dpkg -i $ASC_BASELINE_TMP
          cd /opt/
          pwd
          ls -R
        displayName: show Directory